pool:
  vmImage: ubuntu-latest

trigger:
  - main

variables:
  ACR_NAME: webonyxregistrysouthcentralus
  DOCKER_CONNECTION: DockerHub

steps:
  - script: |
      echo "##vso[task.setvariable variable=IMAGE_TAG]$(date +%Y%B%d)"
    name: SetImageTag

  - task: Docker@2
    name: BuildAndPush
    inputs:
      command: buildAndPush
      repository: webonyx/azuredevops-toolbox
      containerRegistry: $(DOCKER_CONNECTION)
      tags: $(IMAGE_TAG)
