pool:
  vmImage: ubuntu-latest

trigger:
  - main

variables:
  DOCKER_CONNECTION: DockerHub

stages:
  - stage: Build
    jobs:
      - job: PrivateBuild
        pool: Default
        container:
          image: toolbox:latest
          endpoint: webonyxregistrysouthcentralus
        steps:
          - task: Docker@2
            name: BuildAndPush
            inputs:
              command: buildAndPush
              addPipelineData: false
              containerRegistry: webonyxregistrysouthcentralus
              repository: toolbox
              tags: latest

      - job: PublicBuild
        pool:
          vmImage: ubuntu-latest
        steps:
          - script: |
              echo "##vso[task.setvariable variable=IMAGE_TAG]$(date +%Y%B%d)"
            name: SetImageTag

          - task: Docker@2
            name: BuildAndPush
            inputs:
              command: buildAndPush
              addPipelineData: false
              containerRegistry: $(DOCKER_CONNECTION)
              repository: webonyx/azuredevops-toolbox
              tags: |
                latest
                $(IMAGE_TAG)
